SELECT
  SUBSTRING(username FROM POSITION('@' IN username) + 1) AS domain,
  COUNT(*) AS user_count
FROM api_server.users
WHERE 1=1
  AND {{TIMESTAMP_FIELD}} IS NOT NULL
  AND {{TIMESTAMP_FIELD}} >= NOW() - INTERVAL '{{DAYS}} days'
  AND SUBSTRING(username FROM POSITION('@' IN username) + 1) {{GRIDSTATUS_FILTER_STANDALONE}}
  {{INTERNAL_EMAIL_FILTER}}
  {{DOMAIN_FILTER}}
GROUP BY SUBSTRING(username FROM POSITION('@' IN username) + 1)
ORDER BY user_count DESC
LIMIT 20;

